# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'npm'
      - run: |
          cd ./server
          npm ci
      - run: |
          cd ./server
          npm run build --if-present
      - run: |
          cd ./server
          npm test --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artefacts
          path: ./*
